import type { Contact, Deal, PriceEntry } from '@/types';

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'c1',
    name: 'Rajesh Mehta',
    company: 'Mehta Metals Pvt Ltd',
    role: 'Seller',
    commodity: 'Copper Scrap',
    city: 'Delhi',
    state: 'Delhi',
    phone: '9876543210',
    hasWhatsApp: true,
    lastQuotedPrice: '₹620/kg',
    quantity: '10-20 tonnes/month',
    paymentTerms: 'Advance',
    trustScore: 4,
    notes: 'Very reliable, delivers on time. Prefers morning calls.',
    lastContacted: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    followUpDate: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    status: 'Active',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'c2',
    name: 'Priya Sharma',
    company: 'Sharma Industries',
    role: 'Buyer',
    commodity: 'Copper Scrap',
    city: 'Pune',
    state: 'Maharashtra',
    phone: '9123456789',
    hasWhatsApp: true,
    lastQuotedPrice: '₹680/kg',
    quantity: '5-10 tonnes/month',
    paymentTerms: 'Credit 30 days',
    trustScore: 5,
    notes: 'Long-term buyer, always pays on time. Needs ISO-grade material.',
    lastContacted: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    followUpDate: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    status: 'Active',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'c3',
    name: 'Anil Kumar',
    company: 'AK Commodities',
    role: 'Both',
    commodity: 'Aluminium Ingots',
    city: 'Surat',
    state: 'Gujarat',
    phone: '9988776655',
    hasWhatsApp: false,
    lastQuotedPrice: '₹210/kg',
    quantity: '3-5 tonnes/month',
    paymentTerms: '50-50',
    trustScore: 3,
    notes: 'Occasional delays in payment. Verify before big orders.',
    lastContacted: new Date(Date.now() - 14 * 86400000).toISOString().split('T')[0],
    followUpDate: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    status: 'Cold',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
];

export const SEED_DEALS: Deal[] = [
  {
    id: 'd1',
    name: 'Copper Scrap — Delhi to Pune',
    commodity: 'Copper Scrap',
    quantity: 8,
    unit: 'tonnes',
    sellerId: 'c1',
    sellerPrice: 620000,
    buyerId: 'c2',
    buyerPrice: 680000,
    stage: 'Negotiating',
    expectedCloseDate: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
    advanceReceived: false,
    advanceAmount: 0,
    notes: 'Buyer wants sample first. Send 50kg sample this week.',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'd2',
    name: 'Aluminium Ingots — Surat Local',
    commodity: 'Aluminium Ingots',
    quantity: 3,
    unit: 'tonnes',
    sellerId: 'c3',
    sellerPrice: 210000,
    buyerId: 'c3',
    buyerPrice: 225000,
    stage: 'PO Received',
    expectedCloseDate: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
    advanceReceived: true,
    advanceAmount: 200000,
    notes: 'PO signed. Arrange transport by Friday.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const SEED_PRICES: PriceEntry[] = [
  {
    id: 'p1',
    commodity: 'Copper Scrap',
    grade: 'Grade A (99% purity)',
    price: 620,
    unit: 'kg',
    source: 'Phone call',
    contactName: 'Rajesh Mehta',
    city: 'Delhi',
    region: 'North India',
    dateRecorded: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    notes: 'Confirmed price, ready stock of 15 tonnes',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'p2',
    commodity: 'Copper Scrap',
    grade: 'Grade A (99% purity)',
    price: 680,
    unit: 'kg',
    source: 'IndiaMart',
    contactName: 'Sharma Industries',
    city: 'Pune',
    region: 'West India',
    dateRecorded: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    notes: 'Buyer listing, needs 10 tonnes monthly',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'p3',
    commodity: 'Aluminium Ingots',
    grade: 'LM6 Grade',
    price: 205,
    unit: 'kg',
    source: 'Mandi',
    contactName: 'Local Mandi',
    city: 'Surat',
    region: 'West India',
    dateRecorded: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    notes: 'Spot market price',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'p4',
    commodity: 'Aluminium Ingots',
    grade: 'LM6 Grade',
    price: 225,
    unit: 'kg',
    source: 'IndiaMart',
    contactName: 'Anil Kumar',
    city: 'Ahmedabad',
    region: 'West India',
    dateRecorded: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    notes: 'Buyer quote, willing to pick up',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];
